-- MySQL Script generated by MySQL Workbench
-- Tue 27 Oct 2015 11:50:09 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gnbdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gnbdb` ;

-- -----------------------------------------------------
-- Schema gnbdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gnbdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `gnbdb` ;

-- -----------------------------------------------------
-- Table `gnbdb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gnbdb`.`user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `gnbdb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(45) NOT NULL COMMENT '',
  `last_name` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `status` INT NOT NULL DEFAULT 0 COMMENT '',
  `role` INT NOT NULL DEFAULT 0 COMMENT '',
  `pw_salt` VARCHAR(45) NOT NULL COMMENT '',
  `pw_hash` VARCHAR(128) NOT NULL COMMENT '',
  `approved_by_user_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  INDEX `fk_approved_by_idx` (`approved_by_user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_approved_by`
    FOREIGN KEY (`approved_by_user_id`)
    REFERENCES `gnbdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `gnbdb`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gnbdb`.`account` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `gnbdb`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `balance` DECIMAL(14,2) NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_client_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_client`
    FOREIGN KEY (`user_id`)
    REFERENCES `gnbdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000001;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `gnbdb`.`tan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gnbdb`.`tan` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `gnbdb`.`tan` (
  `id` VARCHAR(15) NOT NULL COMMENT '',
  `account_id` INT NOT NULL COMMENT '',
  `used_timestamp` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_bank_account_id_idx` (`account_id` ASC)  COMMENT '',
  CONSTRAINT `fk_bank_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `gnbdb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `gnbdb`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gnbdb`.`transaction` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `gnbdb`.`transaction` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `approved_by_user_id` INT NULL COMMENT '',
  `approved_at` DATETIME NULL COMMENT '',
  `source_account_id` INT NOT NULL COMMENT '',
  `destination_account_id` INT NOT NULL COMMENT '',
  `creation_timestamp` DATETIME NOT NULL COMMENT '',
  `amount` DECIMAL(14,2) NOT NULL COMMENT '',
  `description` VARCHAR(140) NOT NULL COMMENT '',
  `tan_id` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_destination_account_idx` (`destination_account_id` ASC)  COMMENT '',
  INDEX `fk_source_account_idx` (`source_account_id` ASC)  COMMENT '',
  UNIQUE INDEX `tan_id_UNIQUE` (`tan_id` ASC)  COMMENT '',
  INDEX `fk_approved_by_user_idx` (`approved_by_user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_destination_account`
    FOREIGN KEY (`destination_account_id`)
    REFERENCES `gnbdb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_source_account`
    FOREIGN KEY (`source_account_id`)
    REFERENCES `gnbdb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tan`
    FOREIGN KEY (`tan_id`)
    REFERENCES `gnbdb`.`tan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_approved_by_user`
    FOREIGN KEY (`approved_by_user_id`)
    REFERENCES `gnbdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
